"""Schema-level assertions that need no database connection.

These guard the invariants that are easy to break silently in a later refactor —
a dropped CASCADE, a lost unique constraint, a model that stops being registered
and therefore vanishes from every future autogenerated migration.
"""

from app.db.base import Base
from app.models import (
    Exercise,
    ProgressEntry,
    Subscription,
    User,
    Workout,
    WorkoutExercise,
)

EXPECTED_TABLES = {
    "users",
    "workouts",
    "exercises",
    "workout_exercises",
    "progress_entries",
    "subscriptions",
}


def test_all_models_are_registered_on_the_metadata() -> None:
    """A model missing here is a model Alembic autogenerate cannot see."""
    assert EXPECTED_TABLES <= set(Base.metadata.tables)


def test_user_data_cascades_on_account_deletion() -> None:
    """Deleting a user must not leave orphaned training or progress rows."""
    for model in (Workout, ProgressEntry, Subscription):
        fk = next(
            fk for fk in model.__table__.foreign_keys if fk.column.table.name == "users"
        )
        assert fk.ondelete == "CASCADE", f"{model.__name__}.user_id lost its CASCADE"


def test_catalog_exercises_cannot_be_deleted_out_from_under_logged_history() -> None:
    """The catalog FK must RESTRICT — cascading here would erase user history."""
    fk = next(
        fk
        for fk in WorkoutExercise.__table__.foreign_keys
        if fk.column.table.name == "exercises"
    )
    assert fk.ondelete == "RESTRICT"


def test_clerk_id_is_unique() -> None:
    """The Clerk join point. Two rows for one Clerk user would split an account.

    Asserted as a UniqueConstraint specifically, not merely "uniqueness exists":
    `unique=True` on the column would satisfy the intent but emit a unique index
    instead, and the migrations declare a constraint. Keeping the two in the same
    style is what stops autogenerate reporting permanent phantom drift.
    """
    unique_columns = {
        tuple(c.name for c in constraint.columns)
        for constraint in User.__table__.constraints
        if constraint.__class__.__name__ == "UniqueConstraint"
    }
    assert ("clerk_id",) in unique_columns
    assert ("email",) in unique_columns


def test_billing_identity_is_unique() -> None:
    """Two invariants, each protecting against a different failure.

    `user_id` unique is what makes the 1:1 real — two subscription rows for one
    account and every entitlement read becomes a coin toss over which it finds.

    `stripe_customer_id` unique is the sharper one: two accounts sharing a Stripe
    customer would let one user's card entitle another user's account.
    """
    unique_columns = {
        tuple(c.name for c in constraint.columns)
        for constraint in Subscription.__table__.constraints
        if constraint.__class__.__name__ == "UniqueConstraint"
    }
    assert ("user_id",) in unique_columns
    assert ("stripe_customer_id",) in unique_columns
    assert ("stripe_subscription_id",) in unique_columns


def test_subscription_status_is_not_a_native_enum() -> None:
    """Stripe owns this vocabulary, so the database must not constrain it.

    This looks like an oversight — every other controlled vocabulary in the
    schema is a native PG enum (`models/enums.py`) — which is exactly why it is
    asserted. Converting this column to an enum is a natural-looking tidy-up
    that would break billing the day Stripe adds a status: the webhook write
    would fail, and we would go on serving the last known entitlement while
    Stripe billed, or stopped billing, the customer.
    """
    status = Subscription.__table__.columns["status"]
    assert status.type.__class__.__name__ == "String", (
        "subscriptions.status must stay a plain String — see the column's note"
    )


def test_one_progress_entry_per_user_per_day() -> None:
    constraint_columns = {
        tuple(sorted(c.name for c in constraint.columns))
        for constraint in ProgressEntry.__table__.constraints
        if constraint.__class__.__name__ == "UniqueConstraint"
    }
    assert ("recorded_on", "user_id") in constraint_columns


def test_exercise_names_are_unique() -> None:
    """Duplicate catalog rows would silently split a lift's history in two."""
    constraint_columns = {
        tuple(c.name for c in constraint.columns)
        for constraint in Exercise.__table__.constraints
        if constraint.__class__.__name__ == "UniqueConstraint"
    }
    assert ("name",) in constraint_columns


def test_position_is_unique_within_a_workout_but_exercise_is_not() -> None:
    """Repeating a movement in one session is valid training, not a data error."""
    unique_sets = {
        tuple(sorted(c.name for c in constraint.columns))
        for constraint in WorkoutExercise.__table__.constraints
        if constraint.__class__.__name__ == "UniqueConstraint"
    }
    assert ("position", "workout_id") in unique_sets
    assert ("exercise_id", "workout_id") not in unique_sets
