"""Declarative base, constraint naming convention, and shared column mixins."""

import uuid
from datetime import datetime

from sqlalchemy import DateTime, MetaData, func, text
from sqlalchemy.dialects.postgresql import UUID
from sqlalchemy.orm import DeclarativeBase, Mapped, mapped_column

# Postgres auto-names constraints it is not given a name for (`users_email_key`,
# `workouts_user_id_fkey1`, ...). Those names are what a migration must reference
# to DROP a constraint, so leaving them to the database makes downgrades and
# autogenerated diffs unreliable — Alembic cannot drop a constraint whose name it
# cannot predict. Fixing the convention up front makes every constraint name a
# pure function of the table and columns.
NAMING_CONVENTION = {
    "ix": "ix_%(table_name)s_%(column_0_N_name)s",
    "uq": "uq_%(table_name)s_%(column_0_N_name)s",
    "ck": "ck_%(table_name)s_%(constraint_name)s",
    "fk": "fk_%(table_name)s_%(column_0_name)s_%(referred_table_name)s",
    "pk": "pk_%(table_name)s",
}


class Base(DeclarativeBase):
    """Base class for every ORM model.

    SQLAlchemy 2.0 style: `DeclarativeBase` + `Mapped[...]` annotations, which
    give real static types instead of the untyped `Column` attributes of 1.x.
    """

    metadata = MetaData(naming_convention=NAMING_CONVENTION)


class UUIDPrimaryKeyMixin:
    """UUID primary key.

    Why UUID rather than a serial integer:
      - IDs appear in URLs and API payloads; sequential integers leak row counts
        and let anyone enumerate `/workouts/1`, `/workouts/2`, ...
      - Rows can be created client-side or across services without coordinating
        on a sequence.
    Cost: 16 bytes instead of 4/8, and index locality is worse than a monotonic
    key. At this application's scale that is not a real cost.

    The default is set in BOTH places on purpose: Python-side so the ORM knows
    the id before INSERT (no `RETURNING` round trip needed to wire up relations),
    and server-side so hand-written SQL and seed migrations work too.
    `gen_random_uuid()` is built into Postgres 13+ — no pgcrypto extension needed.
    """

    id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True),
        primary_key=True,
        default=uuid.uuid4,
        server_default=text("gen_random_uuid()"),
    )


class TimestampMixin:
    """`created_at` / `updated_at` on every table.

    Both defaults are server-side (`now()`), so the *database clock* is the
    single source of truth. If they were Python-side, an API server with a
    skewed clock — or a row touched by a migration or by psql — would produce
    timestamps that disagree with everything else.

    `timezone=True` maps to `timestamptz`. Postgres stores it as UTC and
    converts on the way out; `timestamp` (without tz) silently discards the
    offset, which is how "the workout happened at 3am" bugs get born.
    """

    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), nullable=False, server_default=func.now()
    )
    updated_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True),
        nullable=False,
        server_default=func.now(),
        # `onupdate` is applied by SQLAlchemy on ORM updates. A DB trigger would
        # also cover raw SQL updates; we accept the ORM-only guarantee for now
        # since all writes go through the API.
        onupdate=func.now(),
    )
