"""Phase 3 initial schema: users, exercises, workouts, workout_exercises, progress_entries

Revision ID: 0001_initial_schema
Revises:
Create Date: 2026-07-20

Hand-written rather than autogenerated. Autogenerate diffs the models against a
live database, and this is the migration that brings the first database into
existence — there is nothing to diff against. From here on, `alembic revision
--autogenerate` is the normal workflow.
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "0001_initial_schema"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


# Postgres ENUM types are schema objects in their own right, created and dropped
# independently of the tables that use them. We create them explicitly and then
# reference them with `create_type=False`, because otherwise the second table to
# use a given type would try to CREATE TYPE again and fail.
goal_enum = postgresql.ENUM(
    "strength",
    "hypertrophy",
    "fat_loss",
    "endurance",
    "general_fitness",
    name="goal",
    create_type=False,
)
experience_level_enum = postgresql.ENUM(
    "beginner", "intermediate", "advanced", name="experience_level", create_type=False
)
muscle_group_enum = postgresql.ENUM(
    "chest",
    "back",
    "shoulders",
    "quads",
    "hamstrings",
    "glutes",
    "calves",
    "biceps",
    "triceps",
    "forearms",
    "core",
    "full_body",
    name="muscle_group",
    create_type=False,
)
equipment_enum = postgresql.ENUM(
    "barbell",
    "dumbbell",
    "machine",
    "cable",
    "bodyweight",
    "kettlebell",
    "band",
    "other",
    name="equipment",
    create_type=False,
)

ALL_ENUMS = (goal_enum, experience_level_enum, muscle_group_enum, equipment_enum)

# Postgres 13+ ships gen_random_uuid() in core, so no pgcrypto extension is
# needed. Supabase runs 15+.
UUID_DEFAULT = sa.text("gen_random_uuid()")


def upgrade() -> None:
    bind = op.get_bind()
    for enum_type in ALL_ENUMS:
        enum_type.create(bind, checkfirst=True)

    # ---------------- users ----------------
    op.create_table(
        "users",
        sa.Column("id", postgresql.UUID(as_uuid=True), server_default=UUID_DEFAULT, nullable=False),
        sa.Column("clerk_id", sa.String(length=255), nullable=False),
        sa.Column("email", sa.String(length=320), nullable=False),
        sa.Column("name", sa.String(length=200), nullable=True),
        sa.Column("height_cm", sa.Numeric(precision=5, scale=2), nullable=True),
        sa.Column("weight_kg", sa.Numeric(precision=5, scale=2), nullable=True),
        sa.Column("goal", goal_enum, nullable=True),
        sa.Column("experience_level", experience_level_enum, nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.PrimaryKeyConstraint("id", name="pk_users"),
        sa.UniqueConstraint("clerk_id", name="uq_users_clerk_id"),
        sa.UniqueConstraint("email", name="uq_users_email"),
        sa.CheckConstraint("height_cm IS NULL OR height_cm > 0", name="height_positive"),
        sa.CheckConstraint("weight_kg IS NULL OR weight_kg > 0", name="weight_positive"),
    )
    # No separate index on clerk_id: the UNIQUE constraint above is backed by a
    # btree on that column, which already serves the per-request auth lookup.

    # ---------------- exercises (catalog) ----------------
    op.create_table(
        "exercises",
        sa.Column("id", postgresql.UUID(as_uuid=True), server_default=UUID_DEFAULT, nullable=False),
        sa.Column("name", sa.String(length=120), nullable=False),
        sa.Column("primary_muscle_group", muscle_group_enum, nullable=False),
        sa.Column("equipment", equipment_enum, nullable=False),
        sa.Column("is_compound", sa.Boolean(), nullable=False, server_default=sa.text("false")),
        sa.Column("instructions", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.PrimaryKeyConstraint("id", name="pk_exercises"),
        sa.UniqueConstraint("name", name="uq_exercises_name"),
    )
    op.create_index("ix_exercises_primary_muscle_group", "exercises", ["primary_muscle_group"])

    # ---------------- workouts ----------------
    op.create_table(
        "workouts",
        sa.Column("id", postgresql.UUID(as_uuid=True), server_default=UUID_DEFAULT, nullable=False),
        sa.Column("user_id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("performed_on", sa.Date(), nullable=False),
        sa.Column("duration_min", sa.Integer(), nullable=True),
        sa.Column("title", sa.String(length=200), nullable=True),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.PrimaryKeyConstraint("id", name="pk_workouts"),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name="fk_workouts_user_id_users", ondelete="CASCADE"
        ),
        sa.CheckConstraint(
            "duration_min IS NULL OR duration_min > 0", name="duration_positive"
        ),
    )
    op.create_index("ix_workouts_user_id_performed_on", "workouts", ["user_id", "performed_on"])

    # ---------------- workout_exercises ----------------
    op.create_table(
        "workout_exercises",
        sa.Column("id", postgresql.UUID(as_uuid=True), server_default=UUID_DEFAULT, nullable=False),
        sa.Column("workout_id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("exercise_id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("position", sa.Integer(), nullable=False),
        sa.Column("sets", sa.Integer(), nullable=False),
        sa.Column("reps", sa.Integer(), nullable=False),
        sa.Column("weight_kg", sa.Numeric(precision=6, scale=2), nullable=True),
        sa.Column("rpe", sa.Numeric(precision=3, scale=1), nullable=True),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.PrimaryKeyConstraint("id", name="pk_workout_exercises"),
        sa.ForeignKeyConstraint(
            ["workout_id"],
            ["workouts.id"],
            name="fk_workout_exercises_workout_id_workouts",
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["exercise_id"],
            ["exercises.id"],
            name="fk_workout_exercises_exercise_id_exercises",
            ondelete="RESTRICT",
        ),
        sa.UniqueConstraint(
            "workout_id", "position", name="uq_workout_exercises_workout_id_position"
        ),
        sa.CheckConstraint("sets > 0", name="sets_positive"),
        sa.CheckConstraint("reps > 0", name="reps_positive"),
        sa.CheckConstraint("position >= 0", name="position_non_negative"),
        sa.CheckConstraint(
            "weight_kg IS NULL OR weight_kg >= 0", name="weight_non_negative"
        ),
        sa.CheckConstraint(
            "rpe IS NULL OR (rpe >= 1 AND rpe <= 10)", name="rpe_in_range"
        ),
    )
    op.create_index("ix_workout_exercises_workout_id", "workout_exercises", ["workout_id"])
    # Postgres does NOT index foreign keys automatically. Without this, the
    # ON DELETE RESTRICT check on `exercises` would sequential-scan the whole
    # log table on every catalog delete.
    op.create_index("ix_workout_exercises_exercise_id", "workout_exercises", ["exercise_id"])

    # ---------------- progress_entries ----------------
    op.create_table(
        "progress_entries",
        sa.Column("id", postgresql.UUID(as_uuid=True), server_default=UUID_DEFAULT, nullable=False),
        sa.Column("user_id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("recorded_on", sa.Date(), nullable=False),
        sa.Column("bodyweight_kg", sa.Numeric(precision=5, scale=2), nullable=True),
        sa.Column("calories", sa.Integer(), nullable=True),
        sa.Column("protein_g", sa.Integer(), nullable=True),
        sa.Column("sleep_hours", sa.Numeric(precision=3, scale=1), nullable=True),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.PrimaryKeyConstraint("id", name="pk_progress_entries"),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name="fk_progress_entries_user_id_users", ondelete="CASCADE"
        ),
        sa.UniqueConstraint(
            "user_id", "recorded_on", name="uq_progress_entries_user_id_recorded_on"
        ),
        sa.CheckConstraint(
            "bodyweight_kg IS NULL OR bodyweight_kg > 0",
            name="bodyweight_positive",
        ),
        sa.CheckConstraint(
            "calories IS NULL OR calories >= 0", name="calories_non_negative"
        ),
        sa.CheckConstraint(
            "protein_g IS NULL OR protein_g >= 0", name="protein_non_negative"
        ),
        sa.CheckConstraint(
            "sleep_hours IS NULL OR (sleep_hours >= 0 AND sleep_hours <= 24)",
            name="sleep_hours_in_range",
        ),
    )


def downgrade() -> None:
    # Reverse dependency order: children before parents, then the enum types
    # (which cannot be dropped while any column still uses them).
    op.drop_table("progress_entries")
    op.drop_index("ix_workout_exercises_exercise_id", table_name="workout_exercises")
    op.drop_index("ix_workout_exercises_workout_id", table_name="workout_exercises")
    op.drop_table("workout_exercises")
    op.drop_index("ix_workouts_user_id_performed_on", table_name="workouts")
    op.drop_table("workouts")
    op.drop_index("ix_exercises_primary_muscle_group", table_name="exercises")
    op.drop_table("exercises")
    op.drop_table("users")

    bind = op.get_bind()
    for enum_type in ALL_ENUMS:
        enum_type.drop(bind, checkfirst=True)
